version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/froogle
    ports:
      - 8000:8000
    image: app:froogle
    container_name: froogle_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - .data/db:/var/lib/postgressql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db