# Generated by Django 3.2.9 on 2022-01-02 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('img', models.ImageField(upload_to='static/')),
                ('description', models.CharField(max_length=10000)),
                ('auctionStart', models.DateTimeField()),
                ('auctionEnd', models.DateTimeField()),
                ('startingBid', models.DecimalField(decimal_places=2, max_digits=128)),
                ('currentBid', models.DecimalField(decimal_places=2, max_digits=128)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saleItems', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('commentItem', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemComments', to='auctions.itemlisting')),
                ('commentter', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='userComments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.DecimalField(decimal_places=2, max_digits=128)),
                ('bidPlaced', models.DateTimeField()),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
