# Generated by Django 3.2.9 on 2022-01-02 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20220102_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemlisting',
            name='seller',
        ),
    ]
