# Generated by Django 3.2.9 on 2022-01-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_itemlisting_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlisting',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
