# Generated by Django 3.2.9 on 2022-01-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_itemlisting_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlisting',
            name='startingBid',
            field=models.DecimalField(decimal_places=2, max_digits=128, null=True),
        ),
    ]
