# Generated by Django 3.2.9 on 2022-01-12 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_startingbid_itemlisting_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlisting',
            name='seller',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='saleItems', to='auctions.user'),
            preserve_default=False,
        ),
    ]
