# Generated by Django 3.2.9 on 2022-01-12 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_itemlisting_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlisting',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='saleItems', to=settings.AUTH_USER_MODEL),
        ),
    ]
