# Generated by Django 3.2.9 on 2022-01-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_itemlisting_itemlistedon'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlisting',
            name='auctionEnd',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemlisting',
            name='auctionStart',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
