# Generated by Django 3.2.9 on 2022-01-15 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_bid_bidplaced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemlisting',
            name='price',
        ),
        migrations.AddField(
            model_name='itemlisting',
            name='highestBid',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, related_name='currentLeads', to='auctions.bid'),
        ),
    ]
