# Generated by Django 3.2.9 on 2022-01-21 15:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20220115_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlisting',
            name='auctionStart',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.AlterField(
            model_name='itemlisting',
            name='highestBid',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.PROTECT, related_name='currentLeads', to='auctions.bid'),
        ),
    ]
