# Generated by Django 3.2.9 on 2022-01-21 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20220121_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlisting',
            name='highestBid',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='currentLeads', to='auctions.bid'),
        ),
    ]
