# Generated by Django 3.2.9 on 2022-01-21 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_itemlisting_highestbid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemlisting',
            name='highestBid',
        ),
        migrations.AddField(
            model_name='bid',
            name='bidItem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.itemlisting'),
        ),
    ]
