# Generated by Django 3.2.9 on 2022-01-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20220121_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlisting',
            name='startingBid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=128, null=True),
        ),
    ]
