# Generated by Django 3.2.9 on 2022-01-22 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_itemlisting_highestbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlisting',
            name='highestBid',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.DO_NOTHING, to='auctions.bid'),
        ),
    ]
