# Generated by Django 3.2.9 on 2022-01-23 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20220123_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bidItem',
        ),
        migrations.AddField(
            model_name='bid',
            name='bidItem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.itemlisting'),
        ),
    ]
