# Generated by Django 3.2.9 on 2022-01-23 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_auto_20220123_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bidItem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bids', to='auctions.itemlisting'),
        ),
    ]
