# Generated by Django 3.2.9 on 2022-01-23 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_alter_bid_biditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bidItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bids', to='auctions.itemlisting'),
        ),
    ]
