# Generated by Django 3.2.9 on 2022-02-01 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0032_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentProfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profileComments', to='auctions.profile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemComments', to='auctions.itemlisting'),
        ),
    ]
