# Generated by Django 3.2.9 on 2022-02-08 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_itemlisting_winningbid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemlisting',
            name='highestBid',
        ),
        migrations.RemoveField(
            model_name='itemlisting',
            name='winningBid',
        ),
    ]
