# Generated by Django 3.2.9 on 2022-02-08 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0035_auto_20220208_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlisting',
            name='highestBid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auctions.bid'),
        ),
    ]
