# Generated by Django 3.2.9 on 2022-02-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0036_itemlisting_highestbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='watch_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='watching', to='auctions.ItemListing'),
        ),
    ]
