# Generated by Django 3.2.9 on 2022-02-10 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0037_profile_watch_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='watch_list',
            new_name='watchlist',
        ),
    ]
