# Generated by Django 3.2.9 on 2022-04-07 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0038_rename_watch_list_profile_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemlisting',
            name='itemListedOn',
        ),
        migrations.AlterField(
            model_name='itemlisting',
            name='auctionStart',
            field=models.DateTimeField(blank=True, default=datetime.datetime.utcnow),
        ),
    ]
