# Generated by Django 3.2.9 on 2022-04-29 13:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0050_auto_20220429_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bidPlaced',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 29, 13, 15, 28, 978815, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='itemlisting',
            name='highestBid',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auctions.bid'),
        ),
    ]
