# Generated by Django 3.2.9 on 2022-04-29 13:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0051_auto_20220429_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bidPlaced',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 29, 13, 15, 46, 20815, tzinfo=utc)),
        ),
    ]
