# Generated by Django 3.2.9 on 2022-09-02 15:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0059_alter_bid_bidplaced'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taglines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagLine', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='bid',
            name='bidPlaced',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 2, 15, 4, 21, 457040, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
