# Generated by Django 3.2.9 on 2022-09-06 10:15

from django.db import migrations

from auctions.models import Category, Taglines


def populate_categories(apps, schema_editor):
    category_list = ['Electronics', 'Toys', 'Vehicles', 'Cats', 'Stationary']
    for category in category_list:
        obj = Category.objects.create(
            name = category
        )
        obj.save()

def populate_taglines(apps, schema_editor):
    tagline_list = ['Inspired by Coral Draw 6', 'A Bid a Day...', 'An Ode to IMPACT', 'Bid Away', 'Bid Today, Live Tomorrow']
    for line in tagline_list:
        obj = Taglines.objects.create(
            tagLine = line
        )
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0060_auto_20220902_1604'),
    ]

    operations = [
        migrations.RunPython(populate_categories),
        migrations.RunPython(populate_taglines),
    ]
