# Generated by Django 3.2.9 on 2022-09-06 10:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0061_auto_20220906_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bidPlaced',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 6, 10, 39, 44, 618530, tzinfo=utc)),
        ),
    ]
