# Generated by Django 3.2.9 on 2022-09-06 13:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0063_alter_bid_bidplaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bidPlaced',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 6, 13, 32, 3, 91984, tzinfo=utc)),
        ),
    ]
