# Generated by Django 3.2.9 on 2022-09-06 15:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0064_alter_bid_bidplaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bidPlaced',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 6, 15, 23, 14, 699791, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='itemlisting',
            name='auctionStart',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
