# Generated by Django 4.1.3 on 2022-11-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0066_alter_bid_bidplaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(max_length=786),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lasts',
            field=models.CharField(max_length=12),
        ),
    ]
